// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnumAllowingAlias int32

const (
	EnumAllowingAlias_UNKNOWN EnumAllowingAlias = 0
	EnumAllowingAlias_STARTED EnumAllowingAlias = 1
	EnumAllowingAlias_RUNNING EnumAllowingAlias = 1
)

var EnumAllowingAlias_name = map[int32]string{
	0: "UNKNOWN",
	1: "STARTED",
	// Duplicate value: 1: "RUNNING",
}

var EnumAllowingAlias_value = map[string]int32{
	"UNKNOWN": 0,
	"STARTED": 1,
	"RUNNING": 1,
}

func (x EnumAllowingAlias) String() string {
	return proto.EnumName(EnumAllowingAlias_name, int32(x))
}

func (EnumAllowingAlias) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

type UserInfo struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Length               int32    `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Cnt                  int32    `protobuf:"varint,3,opt,name=cnt,proto3" json:"cnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserInfo) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *UserInfo) GetCnt() int32 {
	if m != nil {
		return m.Cnt
	}
	return 0
}

// 保留标识符（Reserved）
type Foo struct {
	// Oneof字段就像可选字段， 除了它们会共享内存， 至多一个字段会被设置
	//
	// Types that are valid to be assigned to TestOneof:
	//	*Foo_Name
	//	*Foo_Userinfo
	TestOneof            isFoo_TestOneof `protobuf_oneof:"test_oneof"`
	Width                []int32         `protobuf:"zigzag32,4,rep,packed,name=width,proto3" json:"width,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Foo) Reset()         { *m = Foo{} }
func (m *Foo) String() string { return proto.CompactTextString(m) }
func (*Foo) ProtoMessage()    {}
func (*Foo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *Foo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Foo.Unmarshal(m, b)
}
func (m *Foo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Foo.Marshal(b, m, deterministic)
}
func (m *Foo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Foo.Merge(m, src)
}
func (m *Foo) XXX_Size() int {
	return xxx_messageInfo_Foo.Size(m)
}
func (m *Foo) XXX_DiscardUnknown() {
	xxx_messageInfo_Foo.DiscardUnknown(m)
}

var xxx_messageInfo_Foo proto.InternalMessageInfo

type isFoo_TestOneof interface {
	isFoo_TestOneof()
}

type Foo_Name struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3,oneof"`
}

type Foo_Userinfo struct {
	Userinfo *UserInfo `protobuf:"bytes,3,opt,name=userinfo,proto3,oneof"`
}

func (*Foo_Name) isFoo_TestOneof() {}

func (*Foo_Userinfo) isFoo_TestOneof() {}

func (m *Foo) GetTestOneof() isFoo_TestOneof {
	if m != nil {
		return m.TestOneof
	}
	return nil
}

func (m *Foo) GetName() string {
	if x, ok := m.GetTestOneof().(*Foo_Name); ok {
		return x.Name
	}
	return ""
}

func (m *Foo) GetUserinfo() *UserInfo {
	if x, ok := m.GetTestOneof().(*Foo_Userinfo); ok {
		return x.Userinfo
	}
	return nil
}

func (m *Foo) GetWidth() []int32 {
	if m != nil {
		return m.Width
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Foo) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Foo_Name)(nil),
		(*Foo_Userinfo)(nil),
	}
}

func init() {
	proto.RegisterEnum("proto.EnumAllowingAlias", EnumAllowingAlias_name, EnumAllowingAlias_value)
	proto.RegisterType((*UserInfo)(nil), "proto.UserInfo")
	proto.RegisterType((*Foo)(nil), "proto.Foo")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0xcf, 0x51, 0x4b, 0xc3, 0x30,
	0x10, 0x07, 0xf0, 0xa6, 0x69, 0xb7, 0xee, 0x36, 0x30, 0x0b, 0x43, 0x8a, 0x4f, 0x65, 0x4f, 0x45,
	0x70, 0x0f, 0xfa, 0x2e, 0x54, 0x9c, 0x6e, 0x13, 0x22, 0xc4, 0x15, 0x1f, 0xa5, 0xd3, 0xb4, 0x2b,
	0xb4, 0x39, 0x69, 0x32, 0xf6, 0x05, 0xfc, 0xe0, 0xd2, 0x76, 0xdb, 0x53, 0xf2, 0x3b, 0xee, 0x8e,
	0xff, 0x01, 0x58, 0x65, 0xec, 0xe2, 0xb7, 0x41, 0x8b, 0xdc, 0xef, 0x9e, 0xb9, 0x80, 0x20, 0x35,
	0xaa, 0x59, 0xeb, 0x1c, 0x79, 0x08, 0xc3, 0x5a, 0x19, 0x93, 0x15, 0x2a, 0x24, 0x11, 0x89, 0x47,
	0xf2, 0x4c, 0x7e, 0x0d, 0x83, 0x4a, 0xe9, 0xc2, 0xee, 0x43, 0x37, 0x22, 0xb1, 0x2f, 0x4f, 0xe2,
	0x0c, 0xe8, 0xb7, 0xb6, 0x21, 0xed, 0x8a, 0xed, 0x77, 0xfe, 0x47, 0x80, 0xbe, 0x20, 0xf2, 0x19,
	0x78, 0x3a, 0xab, 0x4f, 0x8b, 0x56, 0x8e, 0xec, 0xc4, 0xef, 0x20, 0x38, 0x18, 0xd5, 0x94, 0x3a,
	0xc7, 0x6e, 0x68, 0x7c, 0x7f, 0xd5, 0xc7, 0x59, 0x9c, 0x43, 0xac, 0x1c, 0x79, 0x69, 0xe1, 0x33,
	0xf0, 0x8f, 0xe5, 0x8f, 0xdd, 0x87, 0x5e, 0x44, 0xe3, 0xa9, 0xec, 0xf1, 0x34, 0xe9, 0xef, 0xf8,
	0x42, 0xad, 0x30, 0xdf, 0x78, 0x81, 0xcb, 0xe8, 0xc6, 0x0b, 0x46, 0x6c, 0x22, 0x69, 0x8e, 0x28,
	0xe9, 0x2e, 0x6b, 0x6e, 0x1f, 0x61, 0xba, 0xd4, 0x87, 0x3a, 0xa9, 0x2a, 0x3c, 0x96, 0xba, 0x48,
	0xaa, 0x32, 0x33, 0x7c, 0x0c, 0xc3, 0x54, 0xbc, 0x89, 0xf7, 0x4f, 0xc1, 0x9c, 0x16, 0x1f, 0xdb,
	0x44, 0x6e, 0x97, 0xcf, 0x8c, 0xb4, 0x90, 0xa9, 0x10, 0x6b, 0xf1, 0xca, 0xc8, 0x8d, 0xcb, 0xc8,
	0x6e, 0xd0, 0xa5, 0x7a, 0xf8, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x97, 0x51, 0x9e, 0x47, 0x32, 0x01,
	0x00, 0x00,
}
